export const INTENTS = {
  CREATE_STRIPE_PAYMENTS_ACCOUNT: 'CREATE_STRIPE_PAYMENTS_ACCOUNT',
  FINISH_STRIPE_PAYMENTS_ONBOARDING: 'FINISH_STRIPE_PAYMENTS_ONBOARDING',
  FINISH_STRIPE_CONNECT_ONBOARDING: 'FINISH_STRIPE_CONNECT_ONBOARDING',
};

export const FETCHER_KEYS = {
  CREATE_STRIPE_PAYMENTS_ACCOUNT: 'CREATE_STRIPE_PAYMENTS_ACCOUNT',
  FINISH_STRIPE_ONBOARDING: 'FINISH_STRIPE_ONBOARDING',
};
