export const INTENTS = {
  CREATE_STRIPE_CUSTOMER_ACCOUNT: 'CREATE_STRIPE_CUSTOMER_ACCOUNT',
  FINISH_STRIPE_CUSTOMER_ONBOARDING: 'FINISH_STRIPE_CUSTOMER_ONBOARDING',
  FINISH_STRIPE_CONNECT_ONBOARDING: 'FINISH_STRIPE_CONNECT_ONBOARDING',
};

export const FETCHER_KEYS = {
  FINISH_STRIPE_CUSTOMER_ONBOARDING: 'FINISH_STRIPE_CUSTOMER_ONBOARDING',
  CREATE_STRIPE_CONNECT_ACCOUNT: 'CREATE_STRIPE_CONNECT_ACCOUNT',
  FINISH_STRIPE_CONNECT_ACCOUNT: 'FINISH_STRIPE_CONNECT_ACCOUNT',
};
