# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "2c3db0b06834a9b20de60ef4b15c8228"
name = "SynqSell"
handle = "synqsell"
application_url = "https://ends-entered-models-recreation.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-3fe7f8c3.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_assigned_fulfillment_orders,read_customers,read_inventory,read_locations,read_metaobject_definitions,read_metaobjects,read_orders,read_product_listings,read_products,read_shipping,read_themes,read_third_party_fulfillment_orders,unauthenticated_read_metaobjects,unauthenticated_read_product_listings,write_assigned_fulfillment_orders,write_draft_orders,write_fulfillments,write_inventory,write_merchant_managed_fulfillment_orders,write_metaobject_definitions,write_metaobjects,write_orders,write_products,write_shipping,write_third_party_fulfillment_orders"

[auth]
redirect_urls = [
  "https://ends-entered-models-recreation.trycloudflare.com/auth/callback",
  "https://ends-entered-models-recreation.trycloudflare.com/auth/shopify/callback",
  "https://ends-entered-models-recreation.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = [
  "app/uninstalled",
  "fulfillment_orders/cancelled",
  "fulfillment_orders/order_routing_complete",
  "fulfillments/create",
  "fulfillments/update",
  "orders/cancelled",
  "products/delete",
  "products/update"
]
  uri = "arn:aws:events:us-east-2::event-source/aws.partner/shopify.com/153436192769/aws"

[pos]
embedded = false
