# More information about the configuration file can be found here:
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html
version = 0.1

[default]
[default.global.parameters]
stack_name = "Synqsell-Dev"

[default.build.parameters]
cached = true
parallel = true
template_file = "infrastructure/template.yaml"


[default.validate.commands]
pre_validate = "bash validate-stacks.sh"

[default.validate.parameters]
lint = true
template_file = "infrastructure/template.yaml"

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND"
confirm_changeset = true
region = "us-east-2"
s3_bucket = "synqsell-sam"
image_repositories = []
template_file = "infrastructure/template.yaml"
parameter_overrides = "Environment=dev ApiKeySecret=dev/apiKeys AppConfigSecret=dev/appConfig"


[default.package.parameters]
resolve_s3 = true

[default.sync.parameters]
watch = true

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"

[prod]
[prod.global.parameters]
stack_name = "SynqSell-Prod"

[prod.deploy.parameters]
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND"
confirm_changeset = true
region = "us-east-2"
s3_bucket = "synqsell-sam-prod"
template_file = "infrastructure/template.yaml"
image_repositories = []
parameter_overrides = "Environment=prod ApiKeySecret=prod/apiKeys AppConfigSecret=prod/appConfig"


[prod.sync]
[prod.sync.parameters]
watch = false
