# More information about the configuration file can be found here:
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html
version = 0.1

[default.build.parameters]
cached = true
parallel = true
template_file = "iam/template.yaml"

[default.validate.parameters]
lint = true
template_file = "iam/template.yaml"


[default.package.parameters]
resolve_s3 = true

[default.sync.parameters]
watch = true

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"

[dev.deploy.parameters]
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND"
confirm_changeset = true
region = "us-east-2"
s3_bucket = "synqsell-sam"
image_repositories = []
template_file = ".aws-sam/build/template.yaml"
parameter_overrides = "Environment=dev ApiKeySecret=dev/apiKeys AppConfigSecret=dev/appConfig"

[staging]
[staging.global.parameters]
stack_name = "SynqSell-Staging"

[staging.deploy.parameters]
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND"
confirm_changeset = true
region = "us-east-2"
s3_bucket = "synqsell-sam-staging"
image_repositories = []
template_file = ".aws-sam/build/template.yaml"
parameter_overrides = "Environment=staging ApiKeySecret=staging/apiKeys AppConfigSecret=staging/appConfig"


[prod]
[prod.build.parameters]
cached = false
parallel = true
template_file = "infrastructure/template.yaml"

[prod.global.parameters]
stack_name = "SynqSell-Prod"

[prod.deploy.parameters]
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND"
confirm_changeset = true
region = "us-east-2"
s3_bucket = "synqsell-sam-prod"
template_file = ".aws-sam/build/template.yaml"
image_repositories = []
parameter_overrides = "Environment=prod ApiKeySecret=prod/apiKeys AppConfigSecret=prod/appConfig"


[prod.sync]
[prod.sync.parameters]
watch = false
