AWSTemplateFormatVersion: "2010-09-09"
Description: >
  Security groups for Resources in VPC

Parameters:
  AppConfigSecret:
    Type: String
  VpcId:
    Type: String

Resources:
  AlbSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: "Security group for ALB"
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - CidrIp: "0.0.0.0/0"
          FromPort: 80
          IpProtocol: "tcp"
          ToPort: 80
        - CidrIp: "0.0.0.0/0"
          FromPort: 443
          IpProtocol: "tcp"
          ToPort: 443

  EcsServiceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for ECS Service
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - Description: Allow inbound traffic from ALB
          FromPort: 3000
          ToPort: 3000
          IpProtocol: tcp
          SourceSecurityGroupId: !Ref AlbSecurityGroup

  BastionHostSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for Bastion host
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Sub "{{resolve:secretsmanager:${AppConfigSecret}:SecretString:myCidrIP}}"

  LambdaSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for Lambda functions
      VpcId: !Ref VpcId

  DatabaseSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for database access
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          SourceSecurityGroupId: !Ref LambdaSecurityGroup
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          SourceSecurityGroupId: !Ref BastionHostSecurityGroup
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          SourceSecurityGroupId: !Ref EcsServiceSecurityGroup
      VpcId: !Ref VpcId

Outputs:
  AlbSecurityGroup:
    Value: !Ref AlbSecurityGroup
  BastionHostSecurityGroup:
    Value: !Ref BastionHostSecurityGroup
  DatabaseSecurityGroup:
    Value: !Ref DatabaseSecurityGroup
  LambdaSecurityGroup:
    Value: !Ref LambdaSecurityGroup
  EcsServiceSecurityGroup:
    Value: !Ref EcsServiceSecurityGroup
